<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BarangTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('barang')->delete();

        \DB::table('barang')->insert(array(
            0 =>
            array(
                'id' => '1',
                'nama' => 'Big Fan',
                'kode' => 'APBFN01',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '100000',
                'qty_total' => '15',
                'qty_ada' => '15',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-09-24 17:03:37',
            ),
            1 =>
            array(
                'id' => '2',
                'nama' => 'Kursi Belajar',
                'kode' => 'APKBJ02',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '10000',
                'qty_total' => '718',
                'qty_ada' => '718',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-09-24 16:13:34',
            ),
            2 =>
            array(
                'id' => '3',
                'nama' => 'Kursi Lipat',
                'kode' => 'APKLP03',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '4000',
                'qty_total' => '3000',
                'qty_ada' => '3000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            3 =>
            array(
                'id' => '4',
                'nama' => 'Kursi Sofa (VIP)/Set (4 Meja + 1 Kursi)',
                'kode' => 'APKSF04',
                'jenis' => '1',
                'satuan' => '2',
                'harga' => '750000',
                'qty_total' => '30',
                'qty_ada' => '30',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            4 =>
            array(
                'id' => '5',
                'nama' => 'Kursi Susun',
                'kode' => 'APKSS05',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '10000',
                'qty_total' => '1497',
                'qty_ada' => '1497',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            5 =>
            array(
                'id' => '6',
                'nama' => 'Cover Kursi Susun Kain Putih',
                'kode' => 'APCKS06',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '1034',
                'qty_ada' => '1034',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            6 =>
            array(
                'id' => '7',
                'nama' => 'Cover Kursi Susun Kain Hitam',
                'kode' => 'APCKS07',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '396',
                'qty_ada' => '396',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            7 =>
            array(
                'id' => '8',
                'nama' => 'Cover Kursi Susun Strech Polos Putih',
                'kode' => 'APCKS08',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '416',
                'qty_ada' => '416',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            8 =>
            array(
                'id' => '9',
                'nama' => 'Cover Kursi Susun Strech Polos Hitam',
                'kode' => 'APCKS09',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '563',
                'qty_ada' => '563',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            9 =>
            array(
                'id' => '10',
                'nama' => 'Cover Kursi Susun Strech Polos Merah',
                'kode' => 'APCKS10',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '91',
                'qty_ada' => '91',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            10 =>
            array(
                'id' => '11',
                'nama' => 'Cover Kursi Susun Strech Polos Biru',
                'kode' => 'APCKS11',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '100',
                'qty_ada' => '100',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            11 =>
            array(
                'id' => '12',
                'nama' => 'Cover Kursi Susun Strech Polos Abu',
                'kode' => 'APCKS12',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '89',
                'qty_ada' => '89',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            12 =>
            array(
                'id' => '13',
                'nama' => 'Pita Kursi Gold',
                'kode' => 'APPKG13',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '287',
                'qty_ada' => '287',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            13 =>
            array(
                'id' => '14',
                'nama' => 'Pita Kursi Silver',
                'kode' => 'APPKS14',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '90',
                'qty_ada' => '90',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            14 =>
            array(
                'id' => '15',
                'nama' => 'Pita Kursi Slayer Merah',
                'kode' => 'APPKS15',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '120',
                'qty_ada' => '120',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            15 =>
            array(
                'id' => '16',
                'nama' => 'Pita Kursi Slayer Marun',
                'kode' => 'APPKS16',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '90',
                'qty_ada' => '90',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            16 =>
            array(
                'id' => '17',
                'nama' => 'Pita Kursi Slayer Hijau',
                'kode' => 'APPKS17',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '90',
                'qty_ada' => '90',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            17 =>
            array(
                'id' => '18',
                'nama' => 'Pita Kursi Slayer Hijau Muda',
                'kode' => 'APPKS18',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '90',
                'qty_ada' => '90',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            18 =>
            array(
                'id' => '19',
                'nama' => 'Pita Kursi Slayer Biru',
                'kode' => 'APPKS19',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '90',
                'qty_ada' => '90',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            19 =>
            array(
                'id' => '20',
                'nama' => 'Pita Kursi Slayer Kuning',
                'kode' => 'APPKS20',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '90',
                'qty_ada' => '90',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            20 =>
            array(
                'id' => '21',
                'nama' => 'Misty Fan',
                'kode' => 'APMFN21',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '350000',
                'qty_total' => '8',
                'qty_ada' => '8',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            21 =>
            array(
                'id' => '22',
                'nama' => 'Meja Bulat 120',
                'kode' => 'APMBS22',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '150',
                'qty_ada' => '150',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            22 =>
            array(
                'id' => '23',
                'nama' => 'Meja Kotak 60 x 120 cm ',
                'kode' => 'APMKK23',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '164',
                'qty_ada' => '164',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            23 =>
            array(
                'id' => '24',
                'nama' => 'Meja Kotak 80 x 120 cm ',
                'kode' => 'APMKS24',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '238',
                'qty_ada' => '238',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            24 =>
            array(
                'id' => '25',
                'nama' => 'Meja Bulat / Kotak + Set Taplak`',
                'kode' => 'APMST25',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '45000',
                'qty_total' => '552',
                'qty_ada' => '552',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            25 =>
            array(
                'id' => '26',
                'nama' => 'Meja Bulat 150 + Set Taplak',
                'kode' => 'APMBS26',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '175000',
                'qty_total' => '29',
                'qty_ada' => '29',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            26 =>
            array(
                'id' => '27',
                'nama' => 'Meja IBM',
                'kode' => 'APIBM27',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '100000',
                'qty_total' => '143',
                'qty_ada' => '143',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            27 =>
            array(
                'id' => '28',
                'nama' => 'Cover Meja IBM',
                'kode' => 'APCMI28',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '125000',
                'qty_total' => '100',
                'qty_ada' => '100',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            28 =>
            array(
                'id' => '29',
                'nama' => 'Taplak Alas Meja Bulat (120cm/150cm)',
                'kode' => 'APTAM29',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '500',
                'qty_ada' => '500',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            29 =>
            array(
                'id' => '30',
                'nama' => 'Taplak Alas Meja Kotak (80cm/60cm)',
                'kode' => 'APTAM30',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '500',
                'qty_ada' => '500',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            30 =>
            array(
                'id' => '31',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Putih',
                'kode' => 'APTPM31',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '550',
                'qty_ada' => '550',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            31 =>
            array(
                'id' => '32',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Krem',
                'kode' => 'APTPM32',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '550',
                'qty_ada' => '550',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            32 =>
            array(
                'id' => '33',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Merah',
                'kode' => 'APTPM33',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '250',
                'qty_ada' => '250',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            33 =>
            array(
                'id' => '34',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Hijau',
                'kode' => 'APTPM34',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '100',
                'qty_ada' => '100',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            34 =>
            array(
                'id' => '35',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Hitam',
                'kode' => 'APTPM35',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '100',
                'qty_ada' => '100',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            35 =>
            array(
                'id' => '36',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Biru',
                'kode' => 'APTPM36',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '250',
                'qty_ada' => '250',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            36 =>
            array(
                'id' => '37',
                'nama' => 'Q Line',
                'kode' => 'APQLN37',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '44',
                'qty_ada' => '44',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            37 =>
            array(
                'id' => '38',
                'nama' => 'Taplak Bulat',
                'kode' => 'APTBL38',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '163',
                'qty_ada' => '163',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            38 =>
            array(
                'id' => '39',
                'nama' => 'Barikade',
                'kode' => 'APBRK39',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '56',
                'qty_ada' => '56',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            39 =>
            array(
                'id' => '40',
                'nama' => 'Mic Wireless',
                'kode' => 'APMCW40',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '4',
                'qty_ada' => '4',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            40 =>
            array(
                'id' => '41',
                'nama' => 'Mic Kabel',
                'kode' => 'APMCK41',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '20000',
                'qty_total' => '8',
                'qty_ada' => '8',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            41 =>
            array(
                'id' => '42',
                'nama' => 'Mimbar',
                'kode' => 'APMBR42',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '75000',
                'qty_total' => '1',
                'qty_ada' => '1',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-09-24 16:13:34',
            ),
            42 =>
            array(
                'id' => '43',
                'nama' => 'Baki Bulat Stainless Besar',
                'kode' => 'PBBBS01',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '8',
                'qty_ada' => '8',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            43 =>
            array(
                'id' => '44',
                'nama' => 'Baki Bulat Stainless Kecil',
                'kode' => 'PBBBS02',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '5',
                'qty_ada' => '5',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            44 =>
            array(
                'id' => '45',
                'nama' => 'Baki Bulat Stainless Oval',
                'kode' => 'PBBBS03',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '20',
                'qty_ada' => '20',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            45 =>
            array(
                'id' => '46',
                'nama' => 'Baki Kaca',
                'kode' => 'PBBKC04',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '35000',
                'qty_total' => '4',
                'qty_ada' => '4',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            46 =>
            array(
                'id' => '47',
                'nama' => 'Cangkir',
                'kode' => 'PBCKR05',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '250',
                'qty_ada' => '250',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            47 =>
            array(
                'id' => '48',
                'nama' => 'Tatakan Cangkir',
                'kode' => 'PBTCK06',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '500',
                'qty_total' => '1200',
                'qty_ada' => '1200',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            48 =>
            array(
                'id' => '49',
                'nama' => 'Coffe Maker',
                'kode' => 'PBCMK07',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '100000',
                'qty_total' => '1',
                'qty_ada' => '1',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            49 =>
            array(
                'id' => '50',
                'nama' => 'Garpu Besar',
                'kode' => 'PBGBS08',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '400',
                'qty_total' => '1070',
                'qty_ada' => '1070',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            50 =>
            array(
                'id' => '51',
                'nama' => 'Garpu Kecil',
                'kode' => 'PBGKC09',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '400',
                'qty_total' => '1300',
                'qty_ada' => '1300',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            51 =>
            array(
                'id' => '52',
                'nama' => 'Garpu Besar Polos',
                'kode' => 'PBGBP10',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '1000',
                'qty_total' => '780',
                'qty_ada' => '780',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            52 =>
            array(
                'id' => '53',
                'nama' => 'Garpu Kecil Polos',
                'kode' => 'PBGKP11',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '400',
                'qty_ada' => '400',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            53 =>
            array(
                'id' => '54',
                'nama' => 'Garpu Hidang',
                'kode' => 'PBGPH12',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '40',
                'qty_ada' => '40',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            54 =>
            array(
                'id' => '55',
                'nama' => 'Gelas Biasa / Soft Drink',
                'kode' => 'PBGBS13',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '600',
                'qty_total' => '1400',
                'qty_ada' => '1400',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            55 =>
            array(
                'id' => '56',
                'nama' => 'Gelas Ice Cream',
                'kode' => 'PBGIC14',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '500',
                'qty_total' => '1250',
                'qty_ada' => '1250',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            56 =>
            array(
                'id' => '57',
                'nama' => 'Gelas Water Goblet',
                'kode' => 'PBGWG15',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '1250',
                'qty_total' => '350',
                'qty_ada' => '350',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            57 =>
            array(
                'id' => '58',
                'nama' => 'Insert',
                'kode' => 'PBINS16',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '100',
                'qty_ada' => '100',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            58 =>
            array(
                'id' => '59',
                'nama' => 'Jepitan',
                'kode' => 'PBJPT17',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '18',
                'qty_ada' => '18',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            59 =>
            array(
                'id' => '60',
                'nama' => 'Mangkuk Soup Cup',
                'kode' => 'PBMSC18',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '1050',
                'qty_ada' => '1050',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            60 =>
            array(
                'id' => '61',
                'nama' => 'Tatakan Soup Cup',
                'kode' => 'PBTSC19',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '500',
                'qty_total' => '300',
                'qty_ada' => '300',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => '1',
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-09-18 22:22:50',
            ),
            61 =>
            array(
                'id' => '62',
                'nama' => 'Mangkuk Baso',
                'kode' => 'PBMKB20',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '600',
                'qty_ada' => '600',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            62 =>
            array(
                'id' => '63',
                'nama' => 'Mangkuk Puding',
                'kode' => 'PBMKP21',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '1800',
                'qty_ada' => '1800',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            63 =>
            array(
                'id' => '64',
                'nama' => 'Mangkuk Cina',
                'kode' => 'PBMKC22',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '350',
                'qty_ada' => '350',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            64 =>
            array(
                'id' => '65',
                'nama' => 'Mangkuk Bulat Besar',
                'kode' => 'PBMBB23',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '8',
                'qty_ada' => '8',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            65 =>
            array(
                'id' => '66',
                'nama' => 'Mangkuk Bulat Kecil',
                'kode' => 'PBMBK24',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '9',
                'qty_ada' => '9',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            66 =>
            array(
                'id' => '67',
                'nama' => 'Pemanas Kotak Besar',
                'kode' => 'PBPKB25',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '28',
                'qty_ada' => '28',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            67 =>
            array(
                'id' => '68',
                'nama' => 'Pemanas Sayur Bulat Kaca',
                'kode' => 'PBPSB26',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '3',
                'qty_ada' => '3',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            68 =>
            array(
                'id' => '69',
                'nama' => 'Pemanas Sayur Bulat Besar',
                'kode' => 'PBPSB27',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '2',
                'qty_ada' => '2',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            69 =>
            array(
                'id' => '70',
                'nama' => 'Pemanas Sayur Bulat Sedang',
                'kode' => 'PBPSB28',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '2',
                'qty_ada' => '2',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            70 =>
            array(
                'id' => '71',
                'nama' => 'Piring Cekung',
                'kode' => 'PBPCK29',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '330',
                'qty_ada' => '330',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            71 =>
            array(
                'id' => '72',
                'nama' => 'Piring Ceper',
                'kode' => 'PBPCP30',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '1750',
                'qty_ada' => '1750',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            72 =>
            array(
                'id' => '73',
                'nama' => 'Pisau Steak Kayu',
                'kode' => 'PBPSK31',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '110',
                'qty_ada' => '110',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            73 =>
            array(
                'id' => '74',
                'nama' => 'Pisau Steak Stainless Panjang',
                'kode' => 'PBPSS32',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '250',
                'qty_ada' => '250',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            74 =>
            array(
                'id' => '75',
                'nama' => 'Pisau Steak Stainless Pendek',
                'kode' => 'PBPSS33',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '210',
                'qty_ada' => '210',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            75 =>
            array(
                'id' => '76',
                'nama' => 'Pisin B&B',
                'kode' => 'PBPBB34',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '1400',
                'qty_ada' => '1400',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            76 =>
            array(
                'id' => '77',
                'nama' => 'Pisin Sate',
                'kode' => 'PBPST35',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '2100',
                'qty_ada' => '2100',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            77 =>
            array(
                'id' => '78',
                'nama' => 'Roll Top Bulat',
                'kode' => 'PBRTB36',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '60000',
                'qty_total' => '17',
                'qty_ada' => '17',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            78 =>
            array(
                'id' => '79',
                'nama' => 'Roll Top Persegi',
                'kode' => 'PBPTP37',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '75000',
                'qty_total' => '29',
                'qty_ada' => '29',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            79 =>
            array(
                'id' => '80',
                'nama' => 'Sendok Besar',
                'kode' => 'PBSBS38',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '400',
                'qty_total' => '1800',
                'qty_ada' => '1800',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            80 =>
            array(
                'id' => '81',
                'nama' => 'Sendok Kecil',
                'kode' => 'PBSKC39',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '400',
                'qty_total' => '120',
                'qty_ada' => '120',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            81 =>
            array(
                'id' => '82',
                'nama' => 'Sendok Besar Polos',
                'kode' => 'PBSBP40',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '1000',
                'qty_total' => '700',
                'qty_ada' => '700',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            82 =>
            array(
                'id' => '83',
                'nama' => 'Sendok Kecil Polos',
                'kode' => 'PBSKP41',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '520',
                'qty_ada' => '520',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            83 =>
            array(
                'id' => '84',
                'nama' => 'Sendok Bebek',
                'kode' => 'PBSBB42',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '350',
                'qty_ada' => '350',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            84 =>
            array(
                'id' => '85',
                'nama' => 'Sendok Kerang Besar',
                'kode' => 'PBSKB43',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '5',
                'qty_ada' => '5',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            85 =>
            array(
                'id' => '86',
                'nama' => 'Sendok Kerang Kecil',
                'kode' => 'PBSKK44',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '20',
                'qty_ada' => '20',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            86 =>
            array(
                'id' => '87',
                'nama' => 'Sendok Hidang',
                'kode' => 'PBSHD45',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '10',
                'qty_ada' => '10',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            87 =>
            array(
                'id' => '88',
                'nama' => 'Sendok Nasi',
                'kode' => 'PBSNS46',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '2',
                'qty_ada' => '2',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            88 =>
            array(
                'id' => '89',
                'nama' => 'Sendok Sayur',
                'kode' => 'PBSSY47',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '7',
                'qty_ada' => '7',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            89 =>
            array(
                'id' => '90',
                'nama' => 'Sendok Soup Cup',
                'kode' => 'PBSSC48',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '700',
                'qty_ada' => '700',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            90 =>
            array(
                'id' => '91',
                'nama' => 'Sendok Soup Cup Polos',
                'kode' => 'PBSSC49',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '1000',
                'qty_total' => '320',
                'qty_ada' => '320',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            91 =>
            array(
                'id' => '92',
                'nama' => 'Siboli',
                'kode' => 'PBSBL50',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '2',
                'qty_ada' => '2',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            92 =>
            array(
                'id' => '93',
                'nama' => 'Soup Warmer Listrik',
                'kode' => 'PBSWL51',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '150000',
                'qty_total' => '3',
                'qty_ada' => '3',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            93 =>
            array(
                'id' => '94',
                'nama' => 'Toples Kerupuk',
                'kode' => 'PBTKR52',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '6',
                'qty_ada' => '6',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            94 =>
            array(
                'id' => '95',
                'nama' => 'Termos Air Stainless 16 Liter',
                'kode' => 'PBTAS53',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '50000',
                'qty_total' => '2',
                'qty_ada' => '2',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            95 =>
            array(
                'id' => '96',
                'nama' => 'Termos Nasi',
                'kode' => 'PBTNS54',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '50000',
                'qty_total' => '2',
                'qty_ada' => '2',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            96 =>
            array(
                'id' => '97',
                'nama' => 'Pergola Stand (Tanpa Meja)',
                'kode' => 'DKPST01',
                'jenis' => '3',
                'satuan' => '2',
                'harga' => '30000',
                'qty_total' => '50',
                'qty_ada' => '50',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            97 =>
            array(
                'id' => '98',
                'nama' => 'Pergola Stand + Set Meja',
                'kode' => 'DKPSS02',
                'jenis' => '3',
                'satuan' => '2',
                'harga' => '75000',
                'qty_total' => '50',
                'qty_ada' => '50',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            98 =>
            array(
                'id' => '99',
                'nama' => 'Permadani',
                'kode' => 'DKPRD03',
                'jenis' => '3',
                'satuan' => '1',
                'harga' => '100000',
                'qty_total' => '22',
                'qty_ada' => '22',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            99 =>
            array(
                'id' => '100',
                'nama' => 'Tenda Standart /',
                'kode' => 'DKTSD04',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '12500',
                'qty_total' => '3000',
                'qty_ada' => '3000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            100 =>
            array(
                'id' => '101',
                'nama' => 'Tenda Plafon / m',
                'kode' => 'DKTPF05',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '15000',
                'qty_total' => '3000',
                'qty_ada' => '3000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            101 =>
            array(
                'id' => '102',
                'nama' => 'Tenda Plafon Rumbe Dekorasi',
                'kode' => 'DKTPR06',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '20000',
                'qty_total' => '3000',
                'qty_ada' => '3000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            102 =>
            array(
                'id' => '103',
                'nama' => 'Tenda Full Dekorasi / m',
                'kode' => 'DKTFD07',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '45000',
                'qty_total' => '3000',
                'qty_ada' => '3000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            103 =>
            array(
                'id' => '104',
                'nama' => 'Tenda Sarnafil (5x5 m)',
                'kode' => 'DKTSR08',
                'jenis' => '3',
                'satuan' => '4',
                'harga' => '600000',
                'qty_total' => '130',
                'qty_ada' => '130',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            104 =>
            array(
                'id' => '105',
                'nama' => 'Tenda Sarnafil (3x3 m)',
                'kode' => 'DKTSR09',
                'jenis' => '3',
                'satuan' => '4',
                'harga' => '400000',
                'qty_total' => '130',
                'qty_ada' => '130',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            105 =>
            array(
                'id' => '106',
                'nama' => 'Tenda Rodder . M ',
                'kode' => 'DKTRD10',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '65000',
                'qty_total' => '1500',
                'qty_ada' => '1500',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            106 =>
            array(
                'id' => '107',
                'nama' => 'Terplas Rungkup / m',
                'kode' => 'DKTPR11',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '5000',
                'qty_total' => '3000',
                'qty_ada' => '3000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            107 =>
            array(
                'id' => '108',
                'nama' => 'Cover Dinding Baru / m',
                'kode' => 'DKCDB12',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '20000',
                'qty_total' => '5000',
                'qty_ada' => '5000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            108 =>
            array(
                'id' => '109',
                'nama' => 'Cover Dinding Second / m',
                'kode' => 'DKCDS13',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '15000',
                'qty_total' => '5000',
                'qty_ada' => '5000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            109 =>
            array(
                'id' => '110',
                'nama' => 'Rumbe Kain Dekorasi  / m',
                'kode' => 'DKRKD14',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '20000',
                'qty_total' => '4000',
                'qty_ada' => '4000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            110 =>
            array(
                'id' => '111',
                'nama' => 'Kain Skat /m',
                'kode' => 'DKKSK15',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '7500',
                'qty_total' => '500',
                'qty_ada' => '500',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            111 =>
            array(
                'id' => '112',
                'nama' => 'Level / Stis / Panggung 1x1 m',
                'kode' => 'DKLSP16',
                'jenis' => '3',
                'satuan' => '1',
                'harga' => '40000',
                'qty_total' => '19',
                'qty_ada' => '19',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            112 =>
            array(
                'id' => '113',
                'nama' => 'Level / Stis / Panggung 1x2 m',
                'kode' => 'DKLSP17',
                'jenis' => '3',
                'satuan' => '1',
                'harga' => '45000',
                'qty_total' => '18',
                'qty_ada' => '18',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            113 =>
            array(
                'id' => '114',
                'nama' => 'Karpet Baru',
                'kode' => 'DKKPB18',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '17500',
                'qty_total' => '3000',
                'qty_ada' => '3000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            114 =>
            array(
                'id' => '115',
                'nama' => 'Karpet Lama',
                'kode' => 'DKDPL19',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '10000',
                'qty_total' => '3000',
                'qty_ada' => '3000',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            115 =>
            array(
                'id' => '116',
                'nama' => 'Terpal 3x3, 4x4, 6x6, 8x8, 10x10 ',
                'kode' => 'DKTRP20',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '50000',
                'qty_total' => '100',
                'qty_ada' => '100',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            116 =>
            array(
                'id' => '117',
                'nama' => 'Tv LCD',
                'kode' => 'DK07',
                'jenis' => '3',
                'satuan' => '4',
                'harga' => '1000000',
                'qty_total' => '3',
                'qty_ada' => '3',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => NULL,
                'updated_by' => NULL,
                'created_by' => '5',
                'created_at' => '2022-09-24 19:38:30',
                'updated_at' => '2022-09-24 19:39:56',
            ),
        ));
    }
}
