<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BarangPengadaanListTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('barang_pengadaan_list')->delete();
        
        \DB::table('barang_pengadaan_list')->insert(array (
            0 => 
            array (
                'id' => '1',
                'harga' => '100000',
                'qty' => '11',
                'barang' => '1',
                'pengadaan' => '1',
                'updated_by' => '1',
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-09-24 15:25:04',
            ),
            1 => 
            array (
                'id' => '2',
                'harga' => '10000',
                'qty' => '718',
                'barang' => '2',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => '3',
                'harga' => '4000',
                'qty' => '3000',
                'barang' => '3',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => '4',
                'harga' => '750000',
                'qty' => '30',
                'barang' => '4',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => '5',
                'harga' => '10000',
                'qty' => '1497',
                'barang' => '5',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => '6',
                'harga' => '5000',
                'qty' => '1034',
                'barang' => '6',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => '7',
                'harga' => '5000',
                'qty' => '396',
                'barang' => '7',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => '8',
                'harga' => '7500',
                'qty' => '416',
                'barang' => '8',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => '9',
                'harga' => '7500',
                'qty' => '563',
                'barang' => '9',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => '10',
                'harga' => '7500',
                'qty' => '91',
                'barang' => '10',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => '11',
                'harga' => '7500',
                'qty' => '100',
                'barang' => '11',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => '12',
                'harga' => '7500',
                'qty' => '89',
                'barang' => '12',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => '13',
                'harga' => '2500',
                'qty' => '287',
                'barang' => '13',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => '14',
                'harga' => '2500',
                'qty' => '90',
                'barang' => '14',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => '15',
                'harga' => '2500',
                'qty' => '120',
                'barang' => '15',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => '16',
                'harga' => '2500',
                'qty' => '90',
                'barang' => '16',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => '17',
                'harga' => '2500',
                'qty' => '90',
                'barang' => '17',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => '18',
                'harga' => '2500',
                'qty' => '90',
                'barang' => '18',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => '19',
                'harga' => '2500',
                'qty' => '90',
                'barang' => '19',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => '20',
                'harga' => '2500',
                'qty' => '90',
                'barang' => '20',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => '21',
                'harga' => '350000',
                'qty' => '8',
                'barang' => '21',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => '22',
                'harga' => '15000',
                'qty' => '150',
                'barang' => '22',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => '23',
                'harga' => '15000',
                'qty' => '164',
                'barang' => '23',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => '24',
                'harga' => '15000',
                'qty' => '238',
                'barang' => '24',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => '25',
                'harga' => '45000',
                'qty' => '552',
                'barang' => '25',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => '26',
                'harga' => '175000',
                'qty' => '29',
                'barang' => '26',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => '27',
                'harga' => '100000',
                'qty' => '143',
                'barang' => '27',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => '28',
                'harga' => '125000',
                'qty' => '100',
                'barang' => '28',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => '29',
                'harga' => '7500',
                'qty' => '500',
                'barang' => '29',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => '30',
                'harga' => '7500',
                'qty' => '500',
                'barang' => '30',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => '31',
                'harga' => '25000',
                'qty' => '550',
                'barang' => '31',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => '32',
                'harga' => '25000',
                'qty' => '550',
                'barang' => '32',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => '33',
                'harga' => '25000',
                'qty' => '250',
                'barang' => '33',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => '34',
                'harga' => '25000',
                'qty' => '100',
                'barang' => '34',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => '35',
                'harga' => '25000',
                'qty' => '100',
                'barang' => '35',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => '36',
                'harga' => '25000',
                'qty' => '250',
                'barang' => '36',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => '37',
                'harga' => '30000',
                'qty' => '44',
                'barang' => '37',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => '38',
                'harga' => '7500',
                'qty' => '163',
                'barang' => '38',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => '39',
                'harga' => '30000',
                'qty' => '56',
                'barang' => '39',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => '40',
                'harga' => '25000',
                'qty' => '4',
                'barang' => '40',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => '41',
                'harga' => '20000',
                'qty' => '8',
                'barang' => '41',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => '42',
                'harga' => '75000',
                'qty' => '1',
                'barang' => '42',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => '43',
                'harga' => '15000',
                'qty' => '8',
                'barang' => '43',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => '44',
                'harga' => '15000',
                'qty' => '5',
                'barang' => '44',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => '45',
                'harga' => '15000',
                'qty' => '20',
                'barang' => '45',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => '46',
                'harga' => '35000',
                'qty' => '4',
                'barang' => '46',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => '47',
                'harga' => '750',
                'qty' => '250',
                'barang' => '47',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => '48',
                'harga' => '500',
                'qty' => '1200',
                'barang' => '48',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => '49',
                'harga' => '100000',
                'qty' => '1',
                'barang' => '49',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => '50',
                'harga' => '400',
                'qty' => '1070',
                'barang' => '50',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => '51',
                'harga' => '400',
                'qty' => '1300',
                'barang' => '51',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => '52',
                'harga' => '1000',
                'qty' => '780',
                'barang' => '52',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => '53',
                'harga' => '750',
                'qty' => '400',
                'barang' => '53',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => '54',
                'harga' => '5000',
                'qty' => '40',
                'barang' => '54',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => '55',
                'harga' => '600',
                'qty' => '1400',
                'barang' => '55',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => '56',
                'harga' => '500',
                'qty' => '1250',
                'barang' => '56',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => '57',
                'harga' => '1250',
                'qty' => '350',
                'barang' => '57',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => '58',
                'harga' => '25000',
                'qty' => '100',
                'barang' => '58',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => '59',
                'harga' => '5000',
                'qty' => '18',
                'barang' => '59',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => '60',
                'harga' => '750',
                'qty' => '1050',
                'barang' => '60',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => '61',
                'harga' => '500',
                'qty' => '300',
                'barang' => '61',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => '62',
                'harga' => '750',
                'qty' => '600',
                'barang' => '62',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => '63',
                'harga' => '750',
                'qty' => '1800',
                'barang' => '63',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => '64',
                'harga' => '750',
                'qty' => '350',
                'barang' => '64',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => '65',
                'harga' => '25000',
                'qty' => '8',
                'barang' => '65',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => '66',
                'harga' => '15000',
                'qty' => '9',
                'barang' => '66',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => '67',
                'harga' => '30000',
                'qty' => '28',
                'barang' => '67',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => '68',
                'harga' => '30000',
                'qty' => '3',
                'barang' => '68',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => '69',
                'harga' => '30000',
                'qty' => '2',
                'barang' => '69',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => '70',
                'harga' => '30000',
                'qty' => '2',
                'barang' => '70',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => '71',
                'harga' => '750',
                'qty' => '330',
                'barang' => '71',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => '72',
                'harga' => '750',
                'qty' => '1750',
                'barang' => '72',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => '73',
                'harga' => '2500',
                'qty' => '110',
                'barang' => '73',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => '74',
                'harga' => '2500',
                'qty' => '250',
                'barang' => '74',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => '75',
                'harga' => '2500',
                'qty' => '210',
                'barang' => '75',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => '76',
                'harga' => '750',
                'qty' => '1400',
                'barang' => '76',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => '77',
                'harga' => '750',
                'qty' => '2100',
                'barang' => '77',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => '78',
                'harga' => '60000',
                'qty' => '17',
                'barang' => '78',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => '79',
                'harga' => '75000',
                'qty' => '29',
                'barang' => '79',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => '80',
                'harga' => '400',
                'qty' => '1800',
                'barang' => '80',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => '81',
                'harga' => '400',
                'qty' => '120',
                'barang' => '81',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => '82',
                'harga' => '1000',
                'qty' => '700',
                'barang' => '82',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => '83',
                'harga' => '750',
                'qty' => '520',
                'barang' => '83',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => '84',
                'harga' => '750',
                'qty' => '350',
                'barang' => '84',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => '85',
                'harga' => '2500',
                'qty' => '5',
                'barang' => '85',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => '86',
                'harga' => '2500',
                'qty' => '20',
                'barang' => '86',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => '87',
                'harga' => '5000',
                'qty' => '10',
                'barang' => '87',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => '88',
                'harga' => '5000',
                'qty' => '2',
                'barang' => '88',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => '89',
                'harga' => '5000',
                'qty' => '7',
                'barang' => '89',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => '90',
                'harga' => '750',
                'qty' => '700',
                'barang' => '90',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => '91',
                'harga' => '1000',
                'qty' => '320',
                'barang' => '91',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => '92',
                'harga' => '30000',
                'qty' => '2',
                'barang' => '92',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => '93',
                'harga' => '150000',
                'qty' => '3',
                'barang' => '93',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => '94',
                'harga' => '25000',
                'qty' => '6',
                'barang' => '94',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => '95',
                'harga' => '50000',
                'qty' => '2',
                'barang' => '95',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => '96',
                'harga' => '50000',
                'qty' => '2',
                'barang' => '96',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => '97',
                'harga' => '30000',
                'qty' => '50',
                'barang' => '97',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => '98',
                'harga' => '75000',
                'qty' => '50',
                'barang' => '98',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => '99',
                'harga' => '100000',
                'qty' => '22',
                'barang' => '99',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => '100',
                'harga' => '12500',
                'qty' => '3000',
                'barang' => '100',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => '101',
                'harga' => '15000',
                'qty' => '3000',
                'barang' => '101',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => '102',
                'harga' => '20000',
                'qty' => '3000',
                'barang' => '102',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => '103',
                'harga' => '45000',
                'qty' => '3000',
                'barang' => '103',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => '104',
                'harga' => '600000',
                'qty' => '130',
                'barang' => '104',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => '105',
                'harga' => '400000',
                'qty' => '130',
                'barang' => '105',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => '106',
                'harga' => '65000',
                'qty' => '1500',
                'barang' => '106',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => '107',
                'harga' => '5000',
                'qty' => '3000',
                'barang' => '107',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => '108',
                'harga' => '20000',
                'qty' => '5000',
                'barang' => '108',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => '109',
                'harga' => '15000',
                'qty' => '5000',
                'barang' => '109',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => '110',
                'harga' => '20000',
                'qty' => '4000',
                'barang' => '110',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => '111',
                'harga' => '7500',
                'qty' => '500',
                'barang' => '111',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => '112',
                'harga' => '40000',
                'qty' => '19',
                'barang' => '112',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => '113',
                'harga' => '45000',
                'qty' => '18',
                'barang' => '113',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => '114',
                'harga' => '17500',
                'qty' => '3000',
                'barang' => '114',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => '115',
                'harga' => '10000',
                'qty' => '3000',
                'barang' => '115',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => '116',
                'harga' => '50000',
                'qty' => '100',
                'barang' => '116',
                'pengadaan' => '1',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => '122',
                'harga' => '100000',
                'qty' => '5',
                'barang' => '1',
                'pengadaan' => '4',
                'updated_by' => '1',
                'created_by' => '1',
                'created_at' => '2022-09-24 16:43:27',
                'updated_at' => '2022-09-24 16:50:13',
            ),
            117 => 
            array (
                'id' => '123',
                'harga' => '1000000',
                'qty' => '3',
                'barang' => '117',
                'pengadaan' => '5',
                'updated_by' => NULL,
                'created_by' => '5',
                'created_at' => '2022-09-24 19:39:56',
                'updated_at' => '2022-09-24 19:39:56',
            ),
            118 => 
            array (
                'id' => '124',
                'harga' => '100000',
                'qty' => '50',
                'barang' => '118',
                'pengadaan' => '6',
                'updated_by' => '1',
                'created_by' => '1',
                'created_at' => '2022-11-12 16:32:05',
                'updated_at' => '2022-11-12 16:33:56',
            ),
            119 => 
            array (
                'id' => '125',
                'harga' => '100000',
                'qty' => '20',
                'barang' => '1',
                'pengadaan' => '6',
                'updated_by' => '1',
                'created_by' => '1',
                'created_at' => '2022-11-12 16:33:10',
                'updated_at' => '2022-11-12 16:33:37',
            ),
            120 => 
            array (
                'id' => '126',
                'harga' => '500000',
                'qty' => '10',
                'barang' => '119',
                'pengadaan' => '7',
                'updated_by' => NULL,
                'created_by' => '5',
                'created_at' => '2022-11-12 17:04:41',
                'updated_at' => '2022-11-12 17:04:41',
            ),
            121 => 
            array (
                'id' => '127',
                'harga' => '500000',
                'qty' => '0',
                'barang' => '119',
                'pengadaan' => '8',
                'updated_by' => NULL,
                'created_by' => '5',
                'created_at' => '2022-11-19 09:57:01',
                'updated_at' => '2022-11-19 09:57:01',
            ),
            122 => 
            array (
                'id' => '128',
                'harga' => '12500',
                'qty' => '0',
                'barang' => '100',
                'pengadaan' => '8',
                'updated_by' => NULL,
                'created_by' => '5',
                'created_at' => '2022-11-19 09:57:01',
                'updated_at' => '2022-11-19 09:57:01',
            ),
        ));
        
        
    }
}