<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BarangTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('barang')->delete();
        
        \DB::table('barang')->insert(array (
            0 => 
            array (
                'id' => '1',
                'nama' => 'Big Fan',
                'kode' => 'APBFN01',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '100000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            1 => 
            array (
                'id' => '2',
                'nama' => 'Kursi Belajar',
                'kode' => 'APKBJ02',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '10000',
                'qty_total' => '0',
                'qty_ada' => '-1',
                'qty_rusak' => '0',
                'qty_disewakan' => '1',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2023-07-16 12:39:43',
            ),
            2 => 
            array (
                'id' => '3',
                'nama' => 'Kursi Lipat',
                'kode' => 'APKLP03',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '4000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            3 => 
            array (
                'id' => '4',
            'nama' => 'Kursi Sofa (VIP)/Set (4 Meja + 1 Kursi)',
                'kode' => 'APKSF04',
                'jenis' => '1',
                'satuan' => '2',
                'harga' => '750000',
                'qty_total' => '0',
                'qty_ada' => '-1',
                'qty_rusak' => '0',
                'qty_disewakan' => '1',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2023-07-16 12:39:43',
            ),
            4 => 
            array (
                'id' => '5',
                'nama' => 'Kursi Susun',
                'kode' => 'APKSS05',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '10000',
                'qty_total' => '0',
                'qty_ada' => '-1',
                'qty_rusak' => '1',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            5 => 
            array (
                'id' => '6',
                'nama' => 'Cover Kursi Susun Kain Putih',
                'kode' => 'APCKS06',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '-1',
                'qty_ada' => '-1',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            6 => 
            array (
                'id' => '7',
                'nama' => 'Cover Kursi Susun Kain Hitam',
                'kode' => 'APCKS07',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            7 => 
            array (
                'id' => '8',
                'nama' => 'Cover Kursi Susun Strech Polos Putih',
                'kode' => 'APCKS08',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            8 => 
            array (
                'id' => '9',
                'nama' => 'Cover Kursi Susun Strech Polos Hitam',
                'kode' => 'APCKS09',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            9 => 
            array (
                'id' => '10',
                'nama' => 'Cover Kursi Susun Strech Polos Merah',
                'kode' => 'APCKS10',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            10 => 
            array (
                'id' => '11',
                'nama' => 'Cover Kursi Susun Strech Polos Biru',
                'kode' => 'APCKS11',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            11 => 
            array (
                'id' => '12',
                'nama' => 'Cover Kursi Susun Strech Polos Abu',
                'kode' => 'APCKS12',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            12 => 
            array (
                'id' => '13',
                'nama' => 'Pita Kursi Gold',
                'kode' => 'APPKG13',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            13 => 
            array (
                'id' => '14',
                'nama' => 'Pita Kursi Silver',
                'kode' => 'APPKS14',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            14 => 
            array (
                'id' => '15',
                'nama' => 'Pita Kursi Slayer Merah',
                'kode' => 'APPKS15',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            15 => 
            array (
                'id' => '16',
                'nama' => 'Pita Kursi Slayer Marun',
                'kode' => 'APPKS16',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            16 => 
            array (
                'id' => '17',
                'nama' => 'Pita Kursi Slayer Hijau',
                'kode' => 'APPKS17',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            17 => 
            array (
                'id' => '18',
                'nama' => 'Pita Kursi Slayer Hijau Muda',
                'kode' => 'APPKS18',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            18 => 
            array (
                'id' => '19',
                'nama' => 'Pita Kursi Slayer Biru',
                'kode' => 'APPKS19',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            19 => 
            array (
                'id' => '20',
                'nama' => 'Pita Kursi Slayer Kuning',
                'kode' => 'APPKS20',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            20 => 
            array (
                'id' => '21',
                'nama' => 'Misty Fan',
                'kode' => 'APMFN21',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '350000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            21 => 
            array (
                'id' => '22',
                'nama' => 'Meja Bulat 120',
                'kode' => 'APMBS22',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            22 => 
            array (
                'id' => '23',
                'nama' => 'Meja Kotak 60 x 120 cm ',
                'kode' => 'APMKK23',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            23 => 
            array (
                'id' => '24',
                'nama' => 'Meja Kotak 80 x 120 cm ',
                'kode' => 'APMKS24',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            24 => 
            array (
                'id' => '25',
                'nama' => 'Meja Bulat / Kotak + Set Taplak`',
                'kode' => 'APMST25',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '45000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            25 => 
            array (
                'id' => '26',
                'nama' => 'Meja Bulat 150 + Set Taplak',
                'kode' => 'APMBS26',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '175000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            26 => 
            array (
                'id' => '27',
                'nama' => 'Meja IBM',
                'kode' => 'APIBM27',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '100000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            27 => 
            array (
                'id' => '28',
                'nama' => 'Cover Meja IBM',
                'kode' => 'APCMI28',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '125000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            28 => 
            array (
                'id' => '29',
            'nama' => 'Taplak Alas Meja Bulat (120cm/150cm)',
                'kode' => 'APTAM29',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            29 => 
            array (
                'id' => '30',
            'nama' => 'Taplak Alas Meja Kotak (80cm/60cm)',
                'kode' => 'APTAM30',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            30 => 
            array (
                'id' => '31',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Putih',
                'kode' => 'APTPM31',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            31 => 
            array (
                'id' => '32',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Krem',
                'kode' => 'APTPM32',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            32 => 
            array (
                'id' => '33',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Merah',
                'kode' => 'APTPM33',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            33 => 
            array (
                'id' => '34',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Hijau',
                'kode' => 'APTPM34',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            34 => 
            array (
                'id' => '35',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Hitam',
                'kode' => 'APTPM35',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            35 => 
            array (
                'id' => '36',
                'nama' => 'Taplak Pinggiran Meja Bulat / Kotak Biru',
                'kode' => 'APTPM36',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            36 => 
            array (
                'id' => '37',
                'nama' => 'Q Line',
                'kode' => 'APQLN37',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            37 => 
            array (
                'id' => '38',
                'nama' => 'Taplak Bulat',
                'kode' => 'APTBL38',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '7500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            38 => 
            array (
                'id' => '39',
                'nama' => 'Barikade',
                'kode' => 'APBRK39',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            39 => 
            array (
                'id' => '40',
                'nama' => 'Mic Wireless',
                'kode' => 'APMCW40',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            40 => 
            array (
                'id' => '41',
                'nama' => 'Mic Kabel',
                'kode' => 'APMCK41',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '20000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            41 => 
            array (
                'id' => '42',
                'nama' => 'Mimbar',
                'kode' => 'APMBR42',
                'jenis' => '1',
                'satuan' => '1',
                'harga' => '75000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            42 => 
            array (
                'id' => '43',
                'nama' => 'Baki Bulat Stainless Besar',
                'kode' => 'PBBBS01',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            43 => 
            array (
                'id' => '44',
                'nama' => 'Baki Bulat Stainless Kecil',
                'kode' => 'PBBBS02',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            44 => 
            array (
                'id' => '45',
                'nama' => 'Baki Bulat Stainless Oval',
                'kode' => 'PBBBS03',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            45 => 
            array (
                'id' => '46',
                'nama' => 'Baki Kaca',
                'kode' => 'PBBKC04',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '35000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            46 => 
            array (
                'id' => '47',
                'nama' => 'Cangkir',
                'kode' => 'PBCKR05',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            47 => 
            array (
                'id' => '48',
                'nama' => 'Tatakan Cangkir',
                'kode' => 'PBTCK06',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            48 => 
            array (
                'id' => '49',
                'nama' => 'Coffe Maker',
                'kode' => 'PBCMK07',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '100000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            49 => 
            array (
                'id' => '50',
                'nama' => 'Garpu Besar',
                'kode' => 'PBGBS08',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '400',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            50 => 
            array (
                'id' => '51',
                'nama' => 'Garpu Kecil',
                'kode' => 'PBGKC09',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '400',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            51 => 
            array (
                'id' => '52',
                'nama' => 'Garpu Besar Polos',
                'kode' => 'PBGBP10',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '1000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            52 => 
            array (
                'id' => '53',
                'nama' => 'Garpu Kecil Polos',
                'kode' => 'PBGKP11',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            53 => 
            array (
                'id' => '54',
                'nama' => 'Garpu Hidang',
                'kode' => 'PBGPH12',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            54 => 
            array (
                'id' => '55',
                'nama' => 'Gelas Biasa / Soft Drink',
                'kode' => 'PBGBS13',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '600',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            55 => 
            array (
                'id' => '56',
                'nama' => 'Gelas Ice Cream',
                'kode' => 'PBGIC14',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            56 => 
            array (
                'id' => '57',
                'nama' => 'Gelas Water Goblet',
                'kode' => 'PBGWG15',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '1250',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            57 => 
            array (
                'id' => '58',
                'nama' => 'Insert',
                'kode' => 'PBINS16',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            58 => 
            array (
                'id' => '59',
                'nama' => 'Jepitan',
                'kode' => 'PBJPT17',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            59 => 
            array (
                'id' => '60',
                'nama' => 'Mangkuk Soup Cup',
                'kode' => 'PBMSC18',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            60 => 
            array (
                'id' => '61',
                'nama' => 'Tatakan Soup Cup',
                'kode' => 'PBTSC19',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => '1',
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            61 => 
            array (
                'id' => '62',
                'nama' => 'Mangkuk Baso',
                'kode' => 'PBMKB20',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            62 => 
            array (
                'id' => '63',
                'nama' => 'Mangkuk Puding',
                'kode' => 'PBMKP21',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            63 => 
            array (
                'id' => '64',
                'nama' => 'Mangkuk Cina',
                'kode' => 'PBMKC22',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            64 => 
            array (
                'id' => '65',
                'nama' => 'Mangkuk Bulat Besar',
                'kode' => 'PBMBB23',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            65 => 
            array (
                'id' => '66',
                'nama' => 'Mangkuk Bulat Kecil',
                'kode' => 'PBMBK24',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '15000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            66 => 
            array (
                'id' => '67',
                'nama' => 'Pemanas Kotak Besar',
                'kode' => 'PBPKB25',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            67 => 
            array (
                'id' => '68',
                'nama' => 'Pemanas Sayur Bulat Kaca',
                'kode' => 'PBPSB26',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            68 => 
            array (
                'id' => '69',
                'nama' => 'Pemanas Sayur Bulat Besar',
                'kode' => 'PBPSB27',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            69 => 
            array (
                'id' => '70',
                'nama' => 'Pemanas Sayur Bulat Sedang',
                'kode' => 'PBPSB28',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            70 => 
            array (
                'id' => '71',
                'nama' => 'Piring Cekung',
                'kode' => 'PBPCK29',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            71 => 
            array (
                'id' => '72',
                'nama' => 'Piring Ceper',
                'kode' => 'PBPCP30',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            72 => 
            array (
                'id' => '73',
                'nama' => 'Pisau Steak Kayu',
                'kode' => 'PBPSK31',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            73 => 
            array (
                'id' => '74',
                'nama' => 'Pisau Steak Stainless Panjang',
                'kode' => 'PBPSS32',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            74 => 
            array (
                'id' => '75',
                'nama' => 'Pisau Steak Stainless Pendek',
                'kode' => 'PBPSS33',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            75 => 
            array (
                'id' => '76',
                'nama' => 'Pisin B&B',
                'kode' => 'PBPBB34',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            76 => 
            array (
                'id' => '77',
                'nama' => 'Pisin Sate',
                'kode' => 'PBPST35',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            77 => 
            array (
                'id' => '78',
                'nama' => 'Roll Top Bulat',
                'kode' => 'PBRTB36',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '60000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            78 => 
            array (
                'id' => '79',
                'nama' => 'Roll Top Persegi',
                'kode' => 'PBPTP37',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '75000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            79 => 
            array (
                'id' => '80',
                'nama' => 'Sendok Besar',
                'kode' => 'PBSBS38',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '400',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            80 => 
            array (
                'id' => '81',
                'nama' => 'Sendok Kecil',
                'kode' => 'PBSKC39',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '400',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            81 => 
            array (
                'id' => '82',
                'nama' => 'Sendok Besar Polos',
                'kode' => 'PBSBP40',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '1000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            82 => 
            array (
                'id' => '83',
                'nama' => 'Sendok Kecil Polos',
                'kode' => 'PBSKP41',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            83 => 
            array (
                'id' => '84',
                'nama' => 'Sendok Bebek',
                'kode' => 'PBSBB42',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            84 => 
            array (
                'id' => '85',
                'nama' => 'Sendok Kerang Besar',
                'kode' => 'PBSKB43',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            85 => 
            array (
                'id' => '86',
                'nama' => 'Sendok Kerang Kecil',
                'kode' => 'PBSKK44',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '2500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            86 => 
            array (
                'id' => '87',
                'nama' => 'Sendok Hidang',
                'kode' => 'PBSHD45',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            87 => 
            array (
                'id' => '88',
                'nama' => 'Sendok Nasi',
                'kode' => 'PBSNS46',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            88 => 
            array (
                'id' => '89',
                'nama' => 'Sendok Sayur',
                'kode' => 'PBSSY47',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '5000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            89 => 
            array (
                'id' => '90',
                'nama' => 'Sendok Soup Cup',
                'kode' => 'PBSSC48',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '750',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            90 => 
            array (
                'id' => '91',
                'nama' => 'Sendok Soup Cup Polos',
                'kode' => 'PBSSC49',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '1000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            91 => 
            array (
                'id' => '92',
                'nama' => 'Siboli',
                'kode' => 'PBSBL50',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '30000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            92 => 
            array (
                'id' => '93',
                'nama' => 'Soup Warmer Listrik',
                'kode' => 'PBSWL51',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '150000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            93 => 
            array (
                'id' => '94',
                'nama' => 'Toples Kerupuk',
                'kode' => 'PBTKR52',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '25000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            94 => 
            array (
                'id' => '95',
                'nama' => 'Termos Air Stainless 16 Liter',
                'kode' => 'PBTAS53',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '50000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            95 => 
            array (
                'id' => '96',
                'nama' => 'Termos Nasi',
                'kode' => 'PBTNS54',
                'jenis' => '2',
                'satuan' => '1',
                'harga' => '50000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            96 => 
            array (
                'id' => '97',
            'nama' => 'Pergola Stand (Tanpa Meja)',
                'kode' => 'DKPST01',
                'jenis' => '3',
                'satuan' => '2',
                'harga' => '30000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            97 => 
            array (
                'id' => '98',
                'nama' => 'Pergola Stand + Set Meja',
                'kode' => 'DKPSS02',
                'jenis' => '3',
                'satuan' => '2',
                'harga' => '75000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            98 => 
            array (
                'id' => '99',
                'nama' => 'Permadani',
                'kode' => 'DKPRD03',
                'jenis' => '3',
                'satuan' => '1',
                'harga' => '100000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            99 => 
            array (
                'id' => '100',
                'nama' => 'Tenda Standart /',
                'kode' => 'DKTSD04',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '12500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            100 => 
            array (
                'id' => '101',
                'nama' => 'Tenda Plafon / m',
                'kode' => 'DKTPF05',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '15000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            101 => 
            array (
                'id' => '102',
                'nama' => 'Tenda Plafon Rumbe Dekorasi',
                'kode' => 'DKTPR06',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '20000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            102 => 
            array (
                'id' => '103',
                'nama' => 'Tenda Full Dekorasi / m',
                'kode' => 'DKTFD07',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '45000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            103 => 
            array (
                'id' => '104',
            'nama' => 'Tenda Sarnafil (5x5 m)',
                'kode' => 'DKTSR08',
                'jenis' => '3',
                'satuan' => '4',
                'harga' => '600000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            104 => 
            array (
                'id' => '105',
            'nama' => 'Tenda Sarnafil (3x3 m)',
                'kode' => 'DKTSR09',
                'jenis' => '3',
                'satuan' => '4',
                'harga' => '400000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            105 => 
            array (
                'id' => '106',
                'nama' => 'Tenda Rodder . M ',
                'kode' => 'DKTRD10',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '65000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            106 => 
            array (
                'id' => '107',
                'nama' => 'Terplas Rungkup / m',
                'kode' => 'DKTPR11',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '5000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            107 => 
            array (
                'id' => '108',
                'nama' => 'Cover Dinding Baru / m',
                'kode' => 'DKCDB12',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '20000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            108 => 
            array (
                'id' => '109',
                'nama' => 'Cover Dinding Second / m',
                'kode' => 'DKCDS13',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '15000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            109 => 
            array (
                'id' => '110',
                'nama' => 'Rumbe Kain Dekorasi  / m',
                'kode' => 'DKRKD14',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '20000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            110 => 
            array (
                'id' => '111',
                'nama' => 'Kain Skat /m',
                'kode' => 'DKKSK15',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '7500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            111 => 
            array (
                'id' => '112',
                'nama' => 'Level / Stis / Panggung 1x1 m',
                'kode' => 'DKLSP16',
                'jenis' => '3',
                'satuan' => '1',
                'harga' => '40000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            112 => 
            array (
                'id' => '113',
                'nama' => 'Level / Stis / Panggung 1x2 m',
                'kode' => 'DKLSP17',
                'jenis' => '3',
                'satuan' => '1',
                'harga' => '45000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            113 => 
            array (
                'id' => '114',
                'nama' => 'Karpet Baru',
                'kode' => 'DKKPB18',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '17500',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            114 => 
            array (
                'id' => '115',
                'nama' => 'Karpet Lama',
                'kode' => 'DKDPL19',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '10000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            115 => 
            array (
                'id' => '116',
                'nama' => 'Terpal 3x3, 4x4, 6x6, 8x8, 10x10 ',
                'kode' => 'DKTRP20',
                'jenis' => '3',
                'satuan' => '3',
                'harga' => '50000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => 'Data Awal',
                'updated_by' => NULL,
                'created_by' => '1',
                'created_at' => '2022-09-17 22:04:43',
                'updated_at' => '2022-12-19 16:27:01',
            ),
            116 => 
            array (
                'id' => '117',
                'nama' => 'Tv LCD',
                'kode' => 'DK07',
                'jenis' => '3',
                'satuan' => '4',
                'harga' => '1000000',
                'qty_total' => '0',
                'qty_ada' => '0',
                'qty_rusak' => '0',
                'qty_disewakan' => '0',
                'keterangan' => NULL,
                'updated_by' => NULL,
                'created_by' => '5',
                'created_at' => '2022-09-24 19:38:30',
                'updated_at' => '2022-12-19 16:26:53',
            ),
        ));
        
        
    }
}