<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GantiRugiPembayaranTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ganti_rugi_pembayaran')->delete();
        
        \DB::table('ganti_rugi_pembayaran')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ganti_rugi_id' => 1,
                'nama' => 'DP',
                'no_surat' => 'GRU/00001',
                'tanggal' => '2022-10-18',
                'oleh' => 'Handip Yusuf Kurniawan',
                'keterangan' => NULL,
                'nominal' => 100000,
                'pembayaran_sebelumnya' => 0,
                'dibayar' => 0,
                'sisa' => 0,
                'status' => 0,
                'pembatalan_alasan' => 'Salah nominal',
                'updated_by' => 1,
                'created_by' => 1,
                'created_at' => '2022-10-18 22:12:55',
                'updated_at' => '2022-10-21 14:57:19',
            ),
            1 => 
            array (
                'id' => 2,
                'ganti_rugi_id' => 2,
                'nama' => 'Pelunasan',
                'no_surat' => 'GRU/00002',
                'tanggal' => '2022-10-22',
                'oleh' => 'Dr Baru',
                'keterangan' => NULL,
                'nominal' => 17500,
                'pembayaran_sebelumnya' => 0,
                'dibayar' => 0,
                'sisa' => 0,
                'status' => 1,
                'pembatalan_alasan' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-10-22 05:14:38',
                'updated_at' => '2022-10-22 05:14:38',
            ),
            2 => 
            array (
                'id' => 3,
                'ganti_rugi_id' => 3,
                'nama' => 'Pertama',
                'no_surat' => 'GRU/00003',
                'tanggal' => '2022-10-22',
                'oleh' => 'Daniel Nugraha',
                'keterangan' => NULL,
                'nominal' => 500000,
                'pembayaran_sebelumnya' => 0,
                'dibayar' => 0,
                'sisa' => 0,
                'status' => 0,
                'pembatalan_alasan' => 'Uang kurang',
                'updated_by' => 5,
                'created_by' => 5,
                'created_at' => '2022-10-22 13:22:40',
                'updated_at' => '2022-10-22 13:23:22',
            ),
            3 => 
            array (
                'id' => 4,
                'ganti_rugi_id' => 4,
                'nama' => 'Pembayaran Ke 2',
                'no_surat' => 'GRU/00004',
                'tanggal' => '2022-10-26',
                'oleh' => 'Customer 15',
                'keterangan' => NULL,
                'nominal' => 50000,
                'pembayaran_sebelumnya' => 0,
                'dibayar' => 0,
                'sisa' => 0,
                'status' => 1,
                'pembatalan_alasan' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-10-26 00:22:08',
                'updated_at' => '2022-10-26 00:22:08',
            ),
            4 => 
            array (
                'id' => 5,
                'ganti_rugi_id' => 5,
                'nama' => 'Testing',
                'no_surat' => 'GRU/00005',
                'tanggal' => '2022-11-07',
                'oleh' => 'Nama Customer Baru',
                'keterangan' => NULL,
                'nominal' => 10000,
                'pembayaran_sebelumnya' => 0,
                'dibayar' => 0,
                'sisa' => 0,
                'status' => 1,
                'pembatalan_alasan' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-11-07 01:40:48',
                'updated_at' => '2022-11-07 01:40:48',
            ),
            5 => 
            array (
                'id' => 6,
                'ganti_rugi_id' => 5,
                'nama' => 'Testing',
                'no_surat' => 'GRU/00006',
                'tanggal' => '2022-11-08',
                'oleh' => 'Nama Customer Baru',
                'keterangan' => NULL,
                'nominal' => 10000,
                'pembayaran_sebelumnya' => 10000,
                'dibayar' => 0,
                'sisa' => 0,
                'status' => 1,
                'pembatalan_alasan' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-11-08 07:15:20',
                'updated_at' => '2022-11-08 07:15:20',
            ),
            6 => 
            array (
                'id' => 7,
                'ganti_rugi_id' => 5,
                'nama' => 'Nama Pembayaran',
                'no_surat' => 'GRU/00007',
                'tanggal' => '2022-11-09',
                'oleh' => 'Oleh',
                'keterangan' => NULL,
                'nominal' => 10,
                'pembayaran_sebelumnya' => 20000,
                'dibayar' => 0,
                'sisa' => 0,
                'status' => 1,
                'pembatalan_alasan' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-11-09 06:31:09',
                'updated_at' => '2022-11-09 06:31:09',
            ),
            7 => 
            array (
                'id' => 8,
                'ganti_rugi_id' => 5,
                'nama' => 'Tes Sisa',
                'no_surat' => 'GRU/00008',
                'tanggal' => '2022-11-09',
                'oleh' => 'Oleh Pembayaran',
                'keterangan' => NULL,
                'nominal' => 20,
                'pembayaran_sebelumnya' => 20010,
                'dibayar' => 0,
                'sisa' => 3869970,
                'status' => 1,
                'pembatalan_alasan' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-11-09 06:33:40',
                'updated_at' => '2022-11-09 06:33:40',
            ),
            8 => 
            array (
                'id' => 9,
                'ganti_rugi_id' => 5,
                'nama' => 'Nama Pembayaran',
                'no_surat' => 'GRU/00009',
                'tanggal' => '2022-11-09',
                'oleh' => 'Pembayaran Oleh',
                'keterangan' => 'Keterangan',
                'nominal' => 20,
                'pembayaran_sebelumnya' => 20030,
                'dibayar' => 0,
                'sisa' => 3869950,
                'status' => 1,
                'pembatalan_alasan' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-11-09 06:34:05',
                'updated_at' => '2022-11-09 06:34:05',
            ),
            9 => 
            array (
                'id' => 10,
                'ganti_rugi_id' => 5,
                'nama' => 'Testing',
                'no_surat' => 'GRU/00010',
                'tanggal' => '2022-11-09',
                'oleh' => 'Nama Customer Baru',
                'keterangan' => NULL,
                'nominal' => 1,
                'pembayaran_sebelumnya' => 20050,
                'dibayar' => 0,
                'sisa' => 3869949,
                'status' => 1,
                'pembatalan_alasan' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-11-09 06:34:54',
                'updated_at' => '2022-11-09 06:34:54',
            ),
            10 => 
            array (
                'id' => 11,
                'ganti_rugi_id' => 5,
                'nama' => '1',
                'no_surat' => 'GRU/00011',
                'tanggal' => '2022-11-09',
                'oleh' => 'Nama Customer Baru',
                'keterangan' => NULL,
                'nominal' => 1,
                'pembayaran_sebelumnya' => 20051,
                'dibayar' => 0,
                'sisa' => 3869948,
                'status' => 1,
                'pembatalan_alasan' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-11-09 06:35:05',
                'updated_at' => '2022-11-09 06:35:05',
            ),
            11 => 
            array (
                'id' => 12,
                'ganti_rugi_id' => 5,
                'nama' => 'Pembayaran Ke 2',
                'no_surat' => 'GRU/00012',
                'tanggal' => '2022-11-09',
                'oleh' => 'Isep Lutpi Nur',
                'keterangan' => NULL,
                'nominal' => 1500000,
                'pembayaran_sebelumnya' => 20052,
                'dibayar' => 1520052,
                'sisa' => 2369948,
                'status' => 1,
                'pembatalan_alasan' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-11-09 07:20:44',
                'updated_at' => '2022-11-09 07:20:44',
            ),
        ));
        
        
    }
}