<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PenyewaanTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('penyewaan')->delete();
        
        \DB::table('penyewaan')->insert(array (
            0 => 
            array (
                'id' => 8,
                'nomor' => 'SP/0008',
                'customer' => 1,
                'lokasi' => 'Gedung Sate',
                'tanggal_kirim' => '2022-10-10',
                'tanggal_pakai_dari' => '2022-10-11',
                'tanggal_pakai_sampai' => '2014-10-01',
                'kepada' => 'Bpk. Daniel Nugraha',
                'tanggal_order' => '2022-10-09',
                'status' => 5,
                'total_harga' => 2900000,
                'dibayar' => 2900000,
                'status_pembayaran' => 1,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => 1,
                'created_by' => 1,
                'created_at' => '2022-10-09 13:57:16',
                'updated_at' => '2022-10-10 01:35:30',
            ),
            1 => 
            array (
                'id' => 9,
                'nomor' => 'SP/0009',
                'customer' => 1,
                'lokasi' => 'Jl. Supratman no 54 gedung b',
                'tanggal_kirim' => '2022-10-12',
                'tanggal_pakai_dari' => '2022-10-13',
                'tanggal_pakai_sampai' => '2022-10-13',
                'kepada' => 'Bpk. Ir. Faisal',
                'tanggal_order' => '2022-10-09',
                'status' => 5,
                'total_harga' => 8850000,
                'dibayar' => 8850000,
                'status_pembayaran' => 1,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-10-09 21:32:40',
                'updated_at' => '2022-10-22 06:17:19',
            ),
            2 => 
            array (
                'id' => 10,
                'nomor' => 'SP/0010',
                'customer' => 2,
                'lokasi' => 'Gedung Serba guna Widyatama.',
                'tanggal_kirim' => '2022-10-07',
                'tanggal_pakai_dari' => '2022-10-08',
                'tanggal_pakai_sampai' => '2022-10-08',
                'kepada' => 'Althaf Subhan',
                'tanggal_order' => '2022-10-10',
                'status' => 5,
                'total_harga' => 3750000,
                'dibayar' => 3750000,
                'status_pembayaran' => 1,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-10-10 00:07:38',
                'updated_at' => '2022-10-10 11:48:45',
            ),
            3 => 
            array (
                'id' => 11,
                'nomor' => 'SP/0011',
                'customer' => 1,
                'lokasi' => 'Alamat 1',
                'tanggal_kirim' => '2022-10-05',
                'tanggal_pakai_dari' => '2022-10-06',
                'tanggal_pakai_sampai' => '2022-10-06',
                'kepada' => 'Customer 1',
                'tanggal_order' => '2022-10-10',
                'status' => 5,
                'total_harga' => 17075000,
                'dibayar' => 17075000,
                'status_pembayaran' => 1,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-10-10 11:22:31',
                'updated_at' => '2022-10-10 13:18:19',
            ),
            4 => 
            array (
                'id' => 12,
                'nomor' => 'SP/0012',
                'customer' => 16,
                'lokasi' => 'Pontianak',
                'tanggal_kirim' => '2022-10-27',
                'tanggal_pakai_dari' => '2022-10-28',
                'tanggal_pakai_sampai' => '2022-10-28',
                'kepada' => 'Daniel Nugraha',
                'tanggal_order' => '2022-10-22',
                'status' => 4,
                'total_harga' => 7550000,
                'dibayar' => 1000000,
                'status_pembayaran' => 0,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 5,
                'created_at' => '2022-10-10 11:38:10',
                'updated_at' => '2022-10-22 11:27:04',
            ),
            5 => 
            array (
                'id' => 13,
                'nomor' => 'SP/0013',
                'customer' => 16,
                'lokasi' => 'Jalan supratman no 50 gedung b',
                'tanggal_kirim' => '2022-10-12',
                'tanggal_pakai_dari' => '2022-10-13',
                'tanggal_pakai_sampai' => '2022-10-13',
                'kepada' => 'Bu. Daniel Nugraha',
                'tanggal_order' => '2022-10-10',
                'status' => 5,
                'total_harga' => 1915000,
                'dibayar' => 1000000,
                'status_pembayaran' => 1,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-10-10 12:12:40',
                'updated_at' => '2022-10-10 14:40:48',
            ),
            6 => 
            array (
                'id' => 14,
                'nomor' => 'SP/0014',
                'customer' => 18,
                'lokasi' => 'Jl. Cikutra No.7, Cikutra, Kec. Cibeunying Kidul, Kota Bandung, Jawa Barat 40124',
                'tanggal_kirim' => '2022-10-07',
                'tanggal_pakai_dari' => '2022-10-08',
                'tanggal_pakai_sampai' => '2022-10-08',
                'kepada' => 'Handip Yusuf Kurniawan',
                'tanggal_order' => '2022-10-15',
                'status' => 5,
                'total_harga' => 9200000,
                'dibayar' => 9200000,
                'status_pembayaran' => 1,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => 1,
                'created_by' => 1,
                'created_at' => '2022-10-15 17:44:39',
                'updated_at' => '2022-10-22 06:17:15',
            ),
            7 => 
            array (
                'id' => 15,
                'nomor' => 'SP/0015',
                'customer' => 17,
                'lokasi' => 'Lengkong',
                'tanggal_kirim' => '2022-10-19',
                'tanggal_pakai_dari' => '2022-10-20',
                'tanggal_pakai_sampai' => '2022-10-20',
                'kepada' => 'Dr Baru',
                'tanggal_order' => '2022-10-18',
                'status' => 5,
                'total_harga' => 8792500,
                'dibayar' => 8792500,
                'status_pembayaran' => 1,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-10-18 22:22:09',
                'updated_at' => '2022-10-22 05:41:08',
            ),
            8 => 
            array (
                'id' => 16,
                'nomor' => 'SP/0016',
                'customer' => 19,
                'lokasi' => 'Lokasi Penyewaan Baru',
                'tanggal_kirim' => '2022-10-28',
                'tanggal_pakai_dari' => '2022-10-29',
                'tanggal_pakai_sampai' => '2022-10-29',
                'kepada' => 'Kepada Penyewa Baru',
                'tanggal_order' => '2022-10-25',
                'status' => 4,
                'total_harga' => 9025000,
                'dibayar' => 5000000,
                'status_pembayaran' => 1,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-10-22 09:07:17',
                'updated_at' => '2022-10-26 00:17:27',
            ),
            9 => 
            array (
                'id' => 17,
                'nomor' => 'SP/0017',
                'customer' => NULL,
                'lokasi' => NULL,
                'tanggal_kirim' => NULL,
                'tanggal_pakai_dari' => NULL,
                'tanggal_pakai_sampai' => NULL,
                'kepada' => NULL,
                'tanggal_order' => NULL,
                'status' => 0,
                'total_harga' => 0,
                'dibayar' => 0,
                'status_pembayaran' => 0,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 5,
                'created_at' => '2022-10-22 09:21:00',
                'updated_at' => '2022-10-22 09:21:00',
            ),
            10 => 
            array (
                'id' => 18,
                'nomor' => 'SP/0018',
                'customer' => 15,
                'lokasi' => 'Alamat 15',
                'tanggal_kirim' => '2022-10-25',
                'tanggal_pakai_dari' => '2022-10-26',
                'tanggal_pakai_sampai' => '2022-10-26',
                'kepada' => 'Customer 15',
                'tanggal_order' => '2022-10-26',
                'status' => 5,
                'total_harga' => 8675000,
                'dibayar' => 5000000,
                'status_pembayaran' => 1,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-10-26 00:00:46',
                'updated_at' => '2022-10-26 00:29:00',
            ),
            11 => 
            array (
                'id' => 19,
                'nomor' => 'SP/0019',
                'customer' => 18,
                'lokasi' => 'Jl. Cikutra No.7, Cikutra, Kec. Cibeunying Kidul, Kota Bandung, Jawa Barat 40124',
                'tanggal_kirim' => '2022-11-03',
                'tanggal_pakai_dari' => '2022-11-04',
                'tanggal_pakai_sampai' => '2022-11-04',
                'kepada' => 'Handip Yusuf Kurniawan',
                'tanggal_order' => '2022-11-04',
                'status' => 5,
                'total_harga' => 100000,
                'dibayar' => 100000,
                'status_pembayaran' => 1,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-11-04 22:54:39',
                'updated_at' => '2022-11-04 22:59:37',
            ),
            12 => 
            array (
                'id' => 20,
                'nomor' => NULL,
                'customer' => NULL,
                'lokasi' => NULL,
                'tanggal_kirim' => NULL,
                'tanggal_pakai_dari' => NULL,
                'tanggal_pakai_sampai' => NULL,
                'kepada' => NULL,
                'tanggal_order' => NULL,
                'status' => 0,
                'total_harga' => 0,
                'dibayar' => 0,
                'status_pembayaran' => 0,
                'batal_keterangan' => NULL,
                'batal_tanggal' => NULL,
                'batal_oleh' => NULL,
                'updated_by' => NULL,
                'created_by' => 1,
                'created_at' => '2022-11-04 23:49:04',
                'updated_at' => '2022-11-04 23:49:04',
            ),
        ));
        
        
    }
}