<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PMenuTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('p_menu')->delete();
        
        \DB::table('p_menu')->insert(array (
            0 => 
            array (
                'id' => '345',
                'parent_id' => NULL,
                'title' => 'Dashboard',
                'icon' => 'fas fa-tachometer-alt',
                'route' => 'admin.dashboard',
                'sequence' => '1',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-09 13:47:23',
            ),
            1 => 
            array (
                'id' => '346',
                'parent_id' => NULL,
                'title' => 'Pengguna Aplikasi',
                'icon' => 'fas fa-users',
                'route' => 'admin.user',
                'sequence' => '15',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            2 => 
            array (
                'id' => '351',
                'parent_id' => NULL,
                'title' => 'Article',
                'icon' => 'fas fa-file-alt',
                'route' => NULL,
                'sequence' => '3',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:16',
            ),
            3 => 
            array (
                'id' => '352',
                'parent_id' => '351',
                'title' => 'Data',
                'icon' => NULL,
                'route' => 'admin.artikel.data',
                'sequence' => '4',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:16',
            ),
            4 => 
            array (
                'id' => '353',
                'parent_id' => '351',
                'title' => 'Category',
                'icon' => NULL,
                'route' => 'admin.artikel.kategori',
                'sequence' => '5',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:16',
            ),
            5 => 
            array (
                'id' => '354',
                'parent_id' => '351',
                'title' => 'Tag',
                'icon' => NULL,
                'route' => 'admin.artikel.tag',
                'sequence' => '6',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:16',
            ),
            6 => 
            array (
                'id' => '360',
                'parent_id' => NULL,
                'title' => 'Galeri',
                'icon' => 'fas fa-images',
                'route' => 'admin.galeri',
                'sequence' => '7',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:16',
            ),
            7 => 
            array (
                'id' => '361',
                'parent_id' => NULL,
                'title' => 'Menu Management',
                'icon' => 'fas fa-stream',
                'route' => NULL,
                'sequence' => '16',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            8 => 
            array (
                'id' => '363',
                'parent_id' => NULL,
                'title' => 'Sosial Media',
                'icon' => 'fas fa-share-alt',
                'route' => 'admin.social_media',
                'sequence' => '9',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:16',
            ),
            9 => 
            array (
                'id' => '364',
                'parent_id' => NULL,
                'title' => 'Contact',
                'icon' => 'fas fa-phone',
                'route' => NULL,
                'sequence' => '10',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:16',
            ),
            10 => 
            array (
                'id' => '367',
                'parent_id' => NULL,
                'title' => 'User Access',
                'icon' => 'fas fa-user-check',
                'route' => NULL,
                'sequence' => '19',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            11 => 
            array (
                'id' => '368',
                'parent_id' => '367',
                'title' => 'Permission',
                'icon' => NULL,
                'route' => 'admin.user_access.permission',
                'sequence' => '20',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            12 => 
            array (
                'id' => '369',
                'parent_id' => '367',
                'title' => 'Role',
                'icon' => NULL,
                'route' => 'admin.user_access.role',
                'sequence' => '21',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            13 => 
            array (
                'id' => '373',
                'parent_id' => NULL,
                'title' => 'Ganti Password',
                'icon' => 'fas fa-key',
                'route' => 'pegawai.password',
                'sequence' => '49',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:50:28',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            14 => 
            array (
                'id' => '386',
                'parent_id' => NULL,
                'title' => 'Logout',
                'icon' => 'fas fa-sign-out-alt',
                'route' => 'logout',
                'sequence' => '50',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-05 23:54:09',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            15 => 
            array (
                'id' => '392',
                'parent_id' => NULL,
                'title' => 'Google Forms',
                'icon' => 'fas fa-user-edit',
                'route' => 'admin.pendaftaran.gform',
                'sequence' => '8',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-08 16:14:54',
                'updated_at' => '2022-09-18 21:18:16',
            ),
            16 => 
            array (
                'id' => '393',
                'parent_id' => NULL,
                'title' => 'Utility',
                'icon' => 'fas fa-tools',
                'route' => NULL,
                'sequence' => '22',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-08 22:41:26',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            17 => 
            array (
                'id' => '394',
                'parent_id' => '393',
                'title' => 'Frontend Notification',
                'icon' => NULL,
                'route' => 'admin.utility.notif_depan_atas',
                'sequence' => '24',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-08 22:41:53',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            18 => 
            array (
                'id' => '397',
                'parent_id' => NULL,
                'title' => 'Pengaturan Halaman',
                'icon' => 'fas fa-wrench',
                'route' => NULL,
                'sequence' => '26',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-14 21:10:57',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            19 => 
            array (
                'id' => '398',
                'parent_id' => '397',
                'title' => 'Admin',
                'icon' => NULL,
                'route' => 'admin.setting.admin',
                'sequence' => '27',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-14 21:11:42',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            20 => 
            array (
                'id' => '399',
                'parent_id' => '397',
                'title' => 'Front',
                'icon' => NULL,
                'route' => 'admin.setting.front',
                'sequence' => '28',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-14 21:52:45',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            21 => 
            array (
                'id' => '400',
                'parent_id' => '397',
                'title' => 'Home',
                'icon' => NULL,
                'route' => 'admin.setting.home',
                'sequence' => '29',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-16 14:55:41',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            22 => 
            array (
                'id' => '401',
                'parent_id' => '393',
                'title' => 'Hari Besar Nasional',
                'icon' => NULL,
                'route' => 'admin.utility.hari_besar_nasional',
                'sequence' => '25',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-17 21:19:05',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            23 => 
            array (
                'id' => '402',
                'parent_id' => '393',
                'title' => 'Admin Notification',
                'icon' => NULL,
                'route' => 'admin.utility.notif_admin_atas',
                'sequence' => '23',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-18 16:42:00',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            24 => 
            array (
                'id' => '404',
                'parent_id' => '403',
                'title' => 'Anggota',
                'icon' => NULL,
                'route' => 'admin.lapooran.anggota',
                'sequence' => '41',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-18 18:55:08',
                'updated_at' => '2022-08-20 14:04:25',
            ),
            25 => 
            array (
                'id' => '405',
                'parent_id' => '361',
                'title' => 'Admin',
                'icon' => NULL,
                'route' => 'admin.menu.admin',
                'sequence' => '17',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-20 14:12:45',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            26 => 
            array (
                'id' => '406',
                'parent_id' => '361',
                'title' => 'Frontend',
                'icon' => NULL,
                'route' => 'admin.menu.frontend',
                'sequence' => '18',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-20 14:16:07',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            27 => 
            array (
                'id' => '407',
                'parent_id' => '364',
                'title' => 'Message',
                'icon' => NULL,
                'route' => 'admin.kontak.message',
                'sequence' => '11',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-21 08:38:20',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            28 => 
            array (
                'id' => '408',
                'parent_id' => '364',
                'title' => 'FAQ',
                'icon' => NULL,
                'route' => 'admin.kontak.faq',
                'sequence' => '12',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-21 08:39:18',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            29 => 
            array (
                'id' => '409',
                'parent_id' => '364',
                'title' => 'List',
                'icon' => NULL,
                'route' => 'admin.kontak.list',
                'sequence' => '13',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-08-21 08:40:08',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            30 => 
            array (
                'id' => '410',
                'parent_id' => NULL,
                'title' => 'Menu Pengguna',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '41',
                'active' => '1',
                'type' => '0',
                'created_at' => '2022-09-09 13:44:38',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            31 => 
            array (
                'id' => '411',
                'parent_id' => NULL,
                'title' => 'Media Dan Informasi',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '2',
                'active' => '1',
                'type' => '0',
                'created_at' => '2022-09-09 13:45:06',
                'updated_at' => '2022-09-18 21:18:16',
            ),
            32 => 
            array (
                'id' => '412',
                'parent_id' => NULL,
                'title' => 'Peralatan',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '14',
                'active' => '1',
                'type' => '0',
                'created_at' => '2022-09-09 13:45:50',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            33 => 
            array (
                'id' => '413',
                'parent_id' => NULL,
                'title' => 'Data Master',
                'icon' => 'fas fa-database',
                'route' => NULL,
                'sequence' => '37',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 19:56:03',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            34 => 
            array (
                'id' => '414',
                'parent_id' => NULL,
                'title' => 'Menu Administrasi',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '30',
                'active' => '1',
                'type' => '0',
                'created_at' => '2022-09-18 19:56:23',
                'updated_at' => '2022-09-18 21:18:17',
            ),
            35 => 
            array (
                'id' => '415',
                'parent_id' => '413',
                'title' => 'Jenis Barang',
                'icon' => NULL,
                'route' => 'admin.data_master.jenis',
                'sequence' => '38',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 19:57:43',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            36 => 
            array (
                'id' => '416',
                'parent_id' => '413',
                'title' => 'Satuan Barang',
                'icon' => NULL,
                'route' => 'admin.data_master.satuan',
                'sequence' => '39',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 19:58:01',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            37 => 
            array (
                'id' => '417',
                'parent_id' => '413',
                'title' => 'Jabatan Pegawai',
                'icon' => NULL,
                'route' => 'admin.data_master.jabatan',
                'sequence' => '40',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 21:03:05',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            38 => 
            array (
                'id' => '418',
                'parent_id' => NULL,
                'title' => 'Barang Sewa',
                'icon' => 'fas fa-box',
                'route' => 'admin.barang.sewa',
                'sequence' => '33',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 21:17:27',
                'updated_at' => '2022-09-22 22:47:39',
            ),
            39 => 
            array (
                'id' => '419',
                'parent_id' => NULL,
                'title' => 'Barang Habis Pakai',
                'icon' => 'fas fa-toolbox',
                'route' => 'admin.barang.habis_pakai',
                'sequence' => '34',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 21:19:13',
                'updated_at' => '2022-09-22 22:47:39',
            ),
            40 => 
            array (
                'id' => '420',
                'parent_id' => NULL,
                'title' => 'Laporan',
                'icon' => 'fas fa-file-alt',
                'route' => NULL,
                'sequence' => '42',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 21:20:43',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            41 => 
            array (
                'id' => '421',
                'parent_id' => '420',
                'title' => 'Pengambilan barang',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '43',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 21:21:44',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            42 => 
            array (
                'id' => '422',
                'parent_id' => '420',
                'title' => 'Pengembalian barang',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '44',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 21:22:19',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            43 => 
            array (
                'id' => '423',
                'parent_id' => '420',
            'title' => 'Pengiriman barang (Surat Jalan)',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '45',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 21:23:37',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            44 => 
            array (
                'id' => '424',
                'parent_id' => '420',
                'title' => 'Barang rusak',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '46',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 21:24:18',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            45 => 
            array (
                'id' => '425',
                'parent_id' => '420',
                'title' => 'Bon pembelian barang habis pakai kas kecil',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '47',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 21:25:45',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            46 => 
            array (
                'id' => '426',
                'parent_id' => '420',
                'title' => 'Bon pembelian barang kas besar',
                'icon' => NULL,
                'route' => NULL,
                'sequence' => '48',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-18 21:26:25',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            47 => 
            array (
                'id' => '427',
                'parent_id' => NULL,
                'title' => 'Karyawan',
                'icon' => 'fas fa-user-edit',
                'route' => 'admin.karyawan',
                'sequence' => '32',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-22 20:51:04',
                'updated_at' => '2022-09-22 22:47:39',
            ),
            48 => 
            array (
                'id' => '428',
                'parent_id' => NULL,
                'title' => 'Customer',
                'icon' => 'far fa-id-badge',
                'route' => 'admin.customer',
                'sequence' => '31',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-22 22:47:27',
                'updated_at' => '2022-09-22 22:55:22',
            ),
            49 => 
            array (
                'id' => '429',
                'parent_id' => NULL,
                'title' => 'Pengadaan Barang',
                'icon' => 'fas fa-truck',
                'route' => NULL,
                'sequence' => '35',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-23 00:08:36',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            50 => 
            array (
                'id' => '430',
                'parent_id' => NULL,
                'title' => 'Pengurangan Barang',
                'icon' => 'fas fa-people-carry',
                'route' => NULL,
                'sequence' => '36',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-23 00:09:48',
                'updated_at' => '2022-09-23 00:10:08',
            ),
            51 => 
            array (
                'id' => '431',
                'parent_id' => '429',
                'title' => 'Barang Sewa',
                'icon' => NULL,
                'route' => 'admin.barang.pengadaan.sewa',
                'sequence' => '50',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-23 00:12:16',
                'updated_at' => '2022-09-23 00:38:35',
            ),
            52 => 
            array (
                'id' => '432',
                'parent_id' => '429',
                'title' => 'Barang Habis Pakai',
                'icon' => NULL,
                'route' => 'admin.barang.pengadaan.habis_pakai',
                'sequence' => '51',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-23 00:13:05',
                'updated_at' => '2022-09-23 00:39:02',
            ),
            53 => 
            array (
                'id' => '433',
                'parent_id' => '430',
                'title' => 'Barang Sewa',
                'icon' => NULL,
                'route' => 'admin.barang.pengurangan.sewa',
                'sequence' => '52',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-23 00:14:48',
                'updated_at' => '2022-09-24 16:18:47',
            ),
            54 => 
            array (
                'id' => '434',
                'parent_id' => '430',
                'title' => 'Barang Habis Pakai',
                'icon' => NULL,
                'route' => 'admin.barang.pengurangan.habis_pakai',
                'sequence' => '53',
                'active' => '1',
                'type' => '1',
                'created_at' => '2022-09-23 00:21:11',
                'updated_at' => '2022-09-24 16:19:12',
            ),
        ));
        
        
    }
}